### ISSUE TITLE
MaSIF calculation input missing

### ISSUE THREAD

**Issue by fisevnen** [lishuya17/PocketAnchorData#3]
Hello, I am working to prepare the input data from step 0, which is the MaSIF feature preparation. When I used the container to precalculate the MaSIF feature, the input folder was empty and the code could not continue. There is no instruction about how to get and name these input data, could you please help me? Thanks a lot!

**Comment by lishuya17** [comment]
Maybe define your input data list and download .pdb files as described in [Step1.Prepare_pdb_files_and_MaSIF_precomputation.ipynb](https://github.com/lishuya17/PocketAnchorData/blob/master/Step1.Prepare_pdb_files_and_MaSIF_precomputation.ipynb)?

**Comment by fisevnen** [comment]
> Maybe define your input data list and download .pdb files as described in [Step1.Prepare_pdb_files_and_MaSIF_precomputation.ipynb](https://github.com/lishuya17/PocketAnchorData/blob/master/Step1.Prepare_pdb_files_and_MaSIF_precomputation.ipynb)?

Thanks for your reply! I have solved it.
