### ISSUE TITLE
About pymol pymesh and python version conflict

### ISSUE THREAD

**Issue by zimeizhng** [lishuya17/PocketAnchorData#4]
After reading your excellent work, I intend to use your protein representation as input for my downstream task. But I am having problems setting up the environment, I would appreciate it if you could let me know which version you have installed (I have had too much trouble setting up this environment) :
Initially, I installed pymol on a conda env with python3.7 : conda install -c conda-forge -c schrodinger Pymol-bundle. However, when I installed pymesh2, I received an error indicating that pymesh2 can only be python3.6. Therefore,  I created a python3.6 environment, then I installed pymol first. However, after trying several versions, there were always conflicts, mainly with python3.6 !  would be very grateful if you could give me any help !

Package wheel conflicts for:
wheel
python=3.6 -> pip -> wheel
pip -> wheel

Package xz conflicts for:
certifi -> python[version='>=3.12,<3.13.0a0'] -> xz[version='>=5.2.10,<6.0a0|>=5.4.2,<6.0a0|>=5.2.8,<6.0a0|>=5.2.6,<6.0a0|>=5.2.5,<6.0a0|>=5.2.4,<6.0a0|>=5.2.3,<6.0a0']
pip -> python[version='>=3.12,<3.13.0a0'] -> xz[version='>=5.2.10,<6.0a0|>=5.4.2,<6.0a0|>=5.2.8,<6.0a0|>=5.2.6,<6.0a0|>=5.2.5,<6.0a0|>=5.2.4,<6.0a0|>=5.2.3,<6.0a0']
setuptools -> python[version='>=3.12,<3.13.0a0'] -> xz[version='>=5.2.10,<6.0a0|>=5.4.2,<6.0a0|>=5.2.6,<6.0a0|>=5.2.5,<6.0a0|>=5.2.4,<6.0a0|>=5.2.8,<6.0a0|>=5.2.3,<6.0a0']
wheel -> python[version='>=3.12,<3.13.0a0'] -> xz[version='>=5.2.10,<6.0a0|>=5.4.2,<6.0a0|>=5.2.8,<6.0a0|>=5.2.6,<6.0a0|>=5.2.5,<6.0a0|>=5.2.4,<6.0a0|>=5.2.3,<6.0a0']
python=3.6 -> xz[version='>=5.2.3,<6.0a0|>=5.2.4,<6.0a0|>=5.2.5,<6.0a0']
pymol==2.3.5 -> libxml2[version='>=2.9.4,<2.10.0a0'] -> xz[version='>=5.2.10,<6.0a0|>=5.2.3,<6.0a0|>=5.2.4,<6.0a0|>=5.2.5,<6.0a0|>=5.2.6,<6.0a0']
xz

Package readline conflicts for:
pymol==2.3.5 -> python[version='>=2.7,<2.8.0a0'] -> readline[version='7.*|>=7.0,<8.0a0|>=8.0,<9.0a0']
wheel -> python[version='>=3.12,<3.13.0a0'] -> readline[version='7.*|>=7.0,<8.0a0|>=8.0,<9.0a0|>=8.2,<9.0a0']
certifi -> python[version='>=3.12,<3.13.0a0'] -> readline[version='7.*|>=7.0,<8.0a0|>=8.0,<9.0a0|>=8.2,<9.0a0']
setuptools -> python[version='>=3.12,<3.13.0a0'] -> readline[version='7.*|>=7.0,<8.0a0|>=8.0,<9.0a0|>=8.2,<9.0a0']
python=3.6 -> readline[version='7.*|>=7.0,<8.0a0|>=8.0,<9.0a0']
sqlite -> readline[version='>=8.0,<9.0a0']
readline
pip -> python[version='>=3.12,<3.13.0a0'] -> readline[version='7.*|>=7.0,<8.0a0|>=8.0,<9.0a0|>=8.2,<9.0a0']

Package _libgcc_mutex conflicts for:
python=3.6 -> libgcc-ng[version='>=7.5.0'] -> _libgcc_mutex[version='*|0.1',build=main]
libgcc-ng -> _libgcc_mutex[version='*|0.1',build=main]
openssl -> libgcc-ng[version='>=7.5.0'] -> _libgcc_mutex[version='*|0.1',build=main]
libffi -> libgcc-ng[version='>=11.2.0'] -> _libgcc_mutex[version='*|0.1',build=main]
ncurses -> libgcc-ng[version='>=11.2.0'] -> _libgcc_mutex[version='*|0.1',build=main]
readline -> libgcc-ng[version='>=11.2.0'] -> _libgcc_mutex[version='*|0.1',build=main]
libgomp -> _libgcc_mutex==0.1=main
_libgcc_mutex
tk -> libgcc-ng[version='>=11.2.0'] -> _libgcc_mutex[version='*|0.1',build=main]
zlib -> libgcc-ng[version='>=11.2.0'] -> _libgcc_mutex[version='*|0.1',build=main]
sqlite -> libgcc-ng[version='>=11.2.0'] -> _libgcc_mutex[version='*|0.1',build=main]
xz -> libgcc-ng[version='>=11.2.0'] -> _libgcc_mutex[version='*|0.1',build=main]
_openmp_mutex -> _libgcc_mutex==0.1=main
pymol==2.3.5 -> libgcc-ng[version='>=7.2.0'] -> _libgcc_mutex[version='*|0.1',build=main]

Package libstdcxx-ng conflicts for:
python=3.6 -> libstdcxx-ng[version='>=7.2.0|>=7.3.0|>=7.5.0']
certifi -> python[version='>=3.8,<3.9.0a0'] -> libstdcxx-ng[version='>=11.2.0|>=7.5.0|>=7.3.0|>=7.2.0']
setuptools -> python[version='>=3.8,<3.9.0a0'] -> libstdcxx-ng[version='>=11.2.0|>=7.5.0|>=7.3.0|>=7.2.0']
readline -> ncurses[version='>=6.2,<7.0a0'] -> libstdcxx-ng[version='>=7.2.0|>=7.3.0']
wheel -> python[version='>=3.9,<3.10.0a0'] -> libstdcxx-ng[version='>=11.2.0|>=7.5.0|>=7.3.0|>=7.2.0']
libstdcxx-ng
pymol==2.3.5 -> glew[version='>=2.0.0,<3.0a0'] -> libstdcxx-ng[version='>=11.2.0|>=7.5.0|>=8.4.0|>=7.3.0']
libffi -> libstdcxx-ng[version='>=11.2.0|>=7.5.0|>=7.3.0|>=7.2.0']
sqlite -> ncurses[version='>=6.2,<7.0a0'] -> libstdcxx-ng[version='>=7.3.0']
pip -> python[version='>=3.9,<3.10.0a0'] -> libstdcxx-ng[version='>=11.2.0|>=7.5.0|>=7.3.0|>=7.2.0']
ncurses -> libstdcxx-ng[version='>=7.2.0|>=7.3.0']
pymol==2.3.5 -> libstdcxx-ng[version='>=7.2.0']

Package bzip2 conflicts for:
setuptools -> python[version='>=3.12,<3.13.0a0'] -> bzip2[version='>=1.0.8,<2.0a0']
pip -> python[version='>=3.12,<3.13.0a0'] -> bzip2[version='>=1.0.8,<2.0a0']
wheel -> python[version='>=3.12,<3.13.0a0'] -> bzip2[version='>=1.0.8,<2.0a0']
certifi -> python[version='>=3.12,<3.13.0a0'] -> bzip2[version='>=1.0.8,<2.0a0']

Package ncurses conflicts for:
sqlite -> readline[version='>=8.0,<9.0a0'] -> ncurses[version='6.0.*|>=6.1,<7.0a0|>=6.3,<7.0a0']
wheel -> python[version='>=3.12,<3.13.0a0'] -> ncurses[version='6.0.*|>=6.0,<7.0a0|>=6.1,<7.0a0|>=6.2,<7.0a0|>=6.3,<7.0a0|>=6.4,<7.0a0']
python=3.6 -> readline[version='>=8.0,<9.0a0'] -> ncurses[version='>=6.3,<7.0a0|>=6.4,<7.0a0']
sqlite -> ncurses[version='>=6.2,<7.0a0|>=6.4,<7.0a0']
certifi -> python[version='>=3.12,<3.13.0a0'] -> ncurses[version='6.0.*|>=6.0,<7.0a0|>=6.1,<7.0a0|>=6.2,<7.0a0|>=6.3,<7.0a0|>=6.4,<7.0a0']
pymol==2.3.5 -> python[version='>=2.7,<2.8.0a0'] -> ncurses[version='6.0.*|>=6.0,<7.0a0|>=6.1,<7.0a0|>=6.2,<7.0a0|>=6.3,<7.0a0']
python=3.6 -> ncurses[version='6.0.*|>=6.0,<7.0a0|>=6.1,<7.0a0|>=6.2,<7.0a0']
pip -> python[version='>=3.12,<3.13.0a0'] -> ncurses[version='6.0.*|>=6.0,<7.0a0|>=6.1,<7.0a0|>=6.2,<7.0a0|>=6.3,<7.0a0|>=6.4,<7.0a0']
setuptools -> python[version='>=3.12,<3.13.0a0'] -> ncurses[version='6.0.*|>=6.0,<7.0a0|>=6.1,<7.0a0|>=6.2,<7.0a0|>=6.3,<7.0a0|>=6.4,<7.0a0']
readline -> ncurses[version='6.0.*|>=6.0,<7.0a0|>=6.1,<7.0a0|>=6.2,<7.0a0|>=6.3,<7.0a0']
ncurses

Package libedit conflicts for:
python=3.6 -> sqlite[version='>=3.33.0,<4.0a0'] -> libedit[version='>=3.1.20170329,<3.2.0a0|>=3.1.20181209,<3.2.0a0|>=3.1.20191231,<3.2.0a0']
sqlite -> libedit[version='>=3.1.20170329,<3.2.0a0|>=3.1.20181209,<3.2.0a0|>=3.1.20191231,<3.2.0a0']

Package openssl conflicts for:
pymol==2.3.5 -> python[version='>=2.7,<2.8.0a0'] -> openssl[version='1.0.*|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.0.2l,<1.0.3a|>=1.1.1k,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1s,<1.1.2a|>=1.1.1q,<1.1.2a|>=1.1.1n,<1.1.2a']
python=3.6 -> openssl[version='1.0.*|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.0.2l,<1.0.3a']
certifi -> python[version='>=3.12,<3.13.0a0'] -> openssl[version='1.0.*|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a|>=1.1.1n,<1.1.2a|>=1.1.1q,<1.1.2a|>=1.1.1s,<1.1.2a|>=1.1.1t,<1.1.2a|>=1.1.1u,<1.1.2a|>=1.1.1v,<1.1.2a|>=3.0.10,<4.0a0|>=3.0.11,<4.0a0|>=3.0.9,<4.0a0|>=3.0.8,<4.0a0|>=1.1.1m,<1.1.2a|>=1.1.1o,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1h,<1.1.2a|>=1.0.2l,<1.0.3a']
openssl
pip -> python[version='>=3.12,<3.13.0a0'] -> openssl[version='1.0.*|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1h,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a|>=1.1.1n,<1.1.2a|>=1.1.1o,<1.1.2a|>=1.1.1q,<1.1.2a|>=1.1.1s,<1.1.2a|>=1.1.1t,<1.1.2a|>=1.1.1u,<1.1.2a|>=1.1.1v,<1.1.2a|>=3.0.10,<4.0a0|>=3.0.11,<4.0a0|>=3.0.9,<4.0a0|>=3.0.8,<4.0a0|>=1.1.1m,<1.1.2a|>=1.0.2l,<1.0.3a']
setuptools -> python[version='>=3.12,<3.13.0a0'] -> openssl[version='1.0.*|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a|>=1.1.1n,<1.1.2a|>=1.1.1q,<1.1.2a|>=1.1.1s,<1.1.2a|>=1.1.1t,<1.1.2a|>=1.1.1u,<1.1.2a|>=1.1.1v,<1.1.2a|>=3.0.10,<4.0a0|>=3.0.11,<4.0a0|>=3.0.9,<4.0a0|>=3.0.8,<4.0a0|>=1.1.1o,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1h,<1.1.2a|>=1.1.1m,<1.1.2a|>=1.0.2l,<1.0.3a']
wheel -> python[version='>=3.12,<3.13.0a0'] -> openssl[version='1.0.*|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1h,<1.1.2a|>=1.1.1i,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a|>=1.1.1l,<1.1.2a|>=1.1.1n,<1.1.2a|>=1.1.1o,<1.1.2a|>=1.1.1q,<1.1.2a|>=1.1.1s,<1.1.2a|>=1.1.1t,<1.1.2a|>=1.1.1u,<1.1.2a|>=1.1.1v,<1.1.2a|>=3.0.10,<4.0a0|>=3.0.11,<4.0a0|>=3.0.9,<4.0a0|>=3.0.8,<4.0a0|>=1.1.1m,<1.1.2a|>=1.0.2l,<1.0.3a']

Package ld_impl_linux-64 conflicts for:
wheel -> python[version='>=3.12,<3.13.0a0'] -> ld_impl_linux-64[version='>=2.35.1|>=2.36.1']
python=3.6 -> ld_impl_linux-64
setuptools -> python[version='>=3.12,<3.13.0a0'] -> ld_impl_linux-64[version='>=2.35.1|>=2.36.1']
ld_impl_linux-64
pip -> python[version='>=3.12,<3.13.0a0'] -> ld_impl_linux-64[version='>=2.35.1|>=2.36.1']
certifi -> python[version='>=3.12,<3.13.0a0'] -> ld_impl_linux-64[version='>=2.35.1|>=2.36.1']
pymol==2.3.5 -> python[version='>=3.6,<3.7.0a0'] -> ld_impl_linux-64

Package setuptools conflicts for:
python=3.6 -> pip -> setuptools
wheel -> setuptools
pip -> setuptools
setuptools

Package ca-certificates conflicts for:
pip -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
wheel -> python -> ca-certificates
certifi -> python -> ca-certificates
python=3.6 -> openssl[version='>=1.1.1k,<1.1.2a'] -> ca-certificates
openssl -> ca-certificates
pymol==2.3.5 -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
setuptools -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
ca-certificates

Package libzlib conflicts for:
python=3.6 -> tk[version='>=8.6.10,<8.7.0a0'] -> libzlib[version='>=1.2.11,<1.3.0a0']
tk -> libzlib[version='>=1.2.11,<1.3.0a0']The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.23=0
  - feature:|@/linux-64::__glibc==2.23=0
  - libffi -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']
  - libgcc-ng -> __glibc[version='>=2.17']
  - ncurses -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']
  - openssl -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - pymol==2.3.5 -> libgcc-ng[version='>=7.2.0'] -> __glibc[version='>=2.17']
  - python=3.6 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - readline -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']
  - sqlite -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']
  - tk -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']
  - xz -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']
  - zlib -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.23

Note that strict channel priority may have removed packages required for satisfiability.

**Comment by lishuya17** [comment]
Hi, I guess maybe you can try to install pymesh2 from its .whl file [pymesh2-0.3-cp37-cp37m-linux_x86_64.whl](https://github.com/PyMesh/PyMesh/releases/download/v0.3/pymesh2-0.3-cp37-cp37m-linux_x86_64.whl)

**Comment by zimeizhng** [comment]
it works! thank you so much!
